wandb_version: 1

'number-epochs:':
  desc: null
  value: 30
lr:
  desc: null
  value: 0.001
data_val:
  desc: null
  value: 2
'similarity:':
  desc: null
  value: cosine
layer:
  desc: null
  value: 3
patch_size:
  desc: null
  value:
  - 8
  - 8
  - 8
data_train:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706643004.882872
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 48
      - 51
      - 55
      - 82
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 5
